version: 2

models:
  - name: silver_orders
    description: "Tabela central de pedidos. Cada linha representa um único pedido feito na plataforma Olist."
    columns:
      - name: order_id
        description: "Identificador único do pedido. Chave primária da tabela."
      - name: customer_id
        description: "Identificador da sessão de compra do cliente. Chave estrangeira para a tabela silver_customers."
      - name: order_status
        description: "Status atual do pedido (ex: delivered, shipped, canceled)."
      - name: purchase_timestamp
        description: "Data e hora em que a compra foi efetuada pelo cliente."
      - name: approved_at
        description: "Data e hora em que o pagamento do pedido foi aprovado."
      - name: delivered_to_carrier_at
        description: "Data e hora em que o pedido foi postado e entregue à transportadora."
      - name: delivered_to_customer_at
        description: "Data e hora em que o pedido foi efetivamente entregue ao cliente."
      - name: estimated_delivery_at
        description: "Data estimada de entrega informada ao cliente no momento da compra."

  - name: silver_order_items
    description: "Tabela de itens de pedido. Cada linha representa um produto específico dentro de um pedido. Um pedido pode ter múltiplos itens."
    columns:
      - name: order_id
        description: "Identificador do pedido ao qual o item pertence."
      - name: order_item_id
        description: "Número sequencial que identifica os itens dentro de um mesmo pedido."
      - name: product_id
        description: "Identificador do produto vendido."
      - name: seller_id
        description: "Identificador do vendedor que comercializou o produto."
      - name: shipping_limit_at
        description: "Data e hora limite para o vendedor enviar o produto."
      - name: price
        description: "Preço do produto (valor unitário)."
      - name: freight_value
        description: "Custo do frete para o item."

  - name: silver_order_payments
    description: "Registros de pagamento dos pedidos. Um único pedido pode ter múltiplas linhas de pagamento (ex: parte no cartão, parte no voucher)."
    columns:
      - name: order_id
        description: "Identificador do pedido relacionado ao pagamento."
      - name: payment_sequential
        description: "Sequência de pagamentos para um mesmo pedido, caso haja mais de um."
      - name: payment_type
        description: "Método de pagamento utilizado (ex: credit_card, boleto, voucher)."
      - name: payment_installments
        description: "Número de parcelas escolhido para o pagamento."
      - name: payment_value
        description: "Valor total deste registro de pagamento."

  - name: silver_order_reviews
    description: "Avaliações (reviews) feitas pelos clientes sobre seus pedidos após a entrega."
    columns:
      - name: review_id
        description: "Identificador único da avaliação."
      - name: order_id
        description: "Identificador do pedido que foi avaliado."
      - name: review_score
        description: "Nota da avaliação atribuída pelo cliente (de 1 a 5)."
      - name: review_comment_title
        description: "Título do comentário da avaliação (opcional)."
      - name: review_comment_message
        description: "Mensagem do comentário da avaliação (opcional)."
      - name: review_creation_timestamp
        description: "Data e hora em que o formulário de avaliação foi enviado pelo cliente."
      - name: review_answer_timestamp
        description: "Data e hora em que a avaliação foi respondida (pelo vendedor ou Olist)."

  - name: silver_products
    description: "Tabela de catálogo com as informações de cada produto vendido na Olist."
    columns:
      - name: product_id
        description: "Identificador único do produto."
      - name: product_category_name
        description: "Nome da categoria do produto em português."
      - name: product_name_length
        description: "Número de caracteres no nome do produto."
      - name: product_description_length
        description: "Número de caracteres na descrição do produto."
      - name: product_photos_qty
        description: "Quantidade de fotos publicadas do produto."
      - name: product_weight_g
        description: "Peso do produto em gramas."
      - name: product_length_cm
        description: "Comprimento do produto em centímetros."
      - name: product_height_cm
        description: "Altura do produto em centímetros."
      - name: product_width_cm
        description: "Largura do produto em centímetros."

  - name: silver_customers
    description: "Dados dos clientes. Cada linha é gerada a cada nova compra, portanto um cliente pode aparecer mais de uma vez."
    columns:
      - name: customer_id
        description: "Identificador da sessão de compra do cliente. Chave primária."
      - name: customer_unique_id
        description: "Identificador único de um cliente. Usado para agrupar todas as compras de uma mesma pessoa."
      - name: customer_zip_code_prefix
        description: "Os 5 primeiros dígitos do CEP do cliente."
      - name: customer_city
        description: "Cidade do cliente."
      - name: customer_state
        description: "Estado (UF) do cliente."

  - name: silver_sellers
    description: "Informações sobre os vendedores (sellers) que utilizam a plataforma Olist."
    columns:
      - name: seller_id
        description: "Identificador único do vendedor."
      - name: seller_zip_code_prefix
        description: "Os 5 primeiros dígitos do CEP do vendedor."
      - name: seller_city
        description: "Cidade do vendedor."
      - name: seller_state
        description: "Estado (UF) do vendedor."

  - name: silver_geolocation
    description: "Dados de geolocalização contendo latitude e longitude para CEPs do Brasil."
    columns:
      - name: zip_code_prefix
        description: "Os 5 primeiros dígitos do CEP."
      - name: latitude
        description: "Coordenada de latitude."
      - name: longitude
        description: "Coordenada de longitude."
      - name: city
        description: "Nome da cidade (com variações de acentuação)."
      - name: state
        description: "Sigla do estado (UF)."

  - name: silver_product_category_translation
    description: "Tabela de tradução (de-para) das categorias de produtos do português para o inglês."
    columns:
      - name: product_category_name
        description: "Nome da categoria em português."
      - name: product_category_name_english
        description: "Nome da categoria em inglês."